name: builder
description: A simple command-line application .
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  lcov_parser: ^0.1.2
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^2.0.0

executables:
  generate_uncovered_test:
