name: health_diary_watches_app
description: The application can help you get fit, monitoring your progress along the way.
publish_to: "none"
version: 0.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  device_info_plus: ^4.0.0
  device_info_plus_tizen: ^1.1.0
  elementary: ^1.0.0
  flex_color_scheme: ^5.0.0

  flutter:
    sdk: flutter

  package_info_plus: ^1.4.0
  package_info_plus_tizen: ^1.0.0

dev_dependencies:
  dart_code_metrics: ^4.8.0
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  golden_toolkit: ^0.13.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
